# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dcopintf.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dcopintf.proto',
  package='GrpcDcopPb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x64\x63opintf.proto\x12\nGrpcDcopPb\"\x1c\n\tPbRequest\x12\x0f\n\x07\x43mdLine\x18\x01 \x01(\t\"\xd4\x02\n\x08PbResult\x12\x0e\n\x06Result\x18\x01 \x01(\r\x12\r\n\x05\x43ount\x18\x02 \x01(\r\x12\r\n\x05\x46ield\x18\x03 \x03(\t\x12%\n\x03Row\x18\x04 \x03(\x0b\x32\x18.GrpcDcopPb.PbResult.Col\x12(\n\x07MsgType\x18\x05 \x01(\x0e\x32\x17.GrpcDcopPb.GrpcMsgType\x12\r\n\x05Title\x18\x06 \x01(\t\x12\x11\n\tstrResult\x18\x07 \x01(\t\x12\x0c\n\x04NeId\x18\x08 \x01(\r\x1a\x63\n\x08\x43olValue\x12\x0c\n\x04Type\x18\x01 \x01(\x05\x12\x0c\n\x04iVal\x18\x02 \x01(\x05\x12\r\n\x05\x64wVal\x18\x03 \x01(\r\x12\r\n\x05qwVal\x18\x04 \x01(\x04\x12\r\n\x05\x64\x62Val\x18\x05 \x01(\x01\x12\x0e\n\x06strVal\x18\x06 \x01(\t\x1a\x34\n\x03\x43ol\x12-\n\x06\x43olVal\x18\x01 \x03(\x0b\x32\x1d.GrpcDcopPb.PbResult.ColValue\"\x1c\n\x07\x45rrcode\x12\x11\n\tdwErrcode\x18\x01 \x01(\r*u\n\x0bGrpcMsgType\x12\x14\n\x10GRPCMSGTYPE_BCMD\x10\x00\x12\x16\n\x12GRPCMSGTYPE_STRCMD\x10\x01\x12\x1b\n\x17GRPCMSGTYPE_NOTIFYEVENT\x10\x02\x12\x1b\n\x17GRPCMSGTYPE_REPORTALARM\x10\x03\x32\x92\x01\n\x0bGrpcRequest\x12?\n\x0eProcessRequest\x12\x15.GrpcDcopPb.PbRequest\x1a\x14.GrpcDcopPb.PbResult\"\x00\x12\x42\n\x11\x43ommandLineResult\x12\x15.GrpcDcopPb.PbRequest\x1a\x14.GrpcDcopPb.PbResult\"\x00\x32\x43\n\nNotify2NCS\x12\x35\n\x06Notify\x12\x14.GrpcDcopPb.PbResult\x1a\x13.GrpcDcopPb.Errcode\"\x00\x62\x06proto3')
)

_GRPCMSGTYPE = _descriptor.EnumDescriptor(
  name='GrpcMsgType',
  full_name='GrpcDcopPb.GrpcMsgType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GRPCMSGTYPE_BCMD', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GRPCMSGTYPE_STRCMD', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GRPCMSGTYPE_NOTIFYEVENT', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GRPCMSGTYPE_REPORTALARM', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=433,
  serialized_end=550,
)
_sym_db.RegisterEnumDescriptor(_GRPCMSGTYPE)

GrpcMsgType = enum_type_wrapper.EnumTypeWrapper(_GRPCMSGTYPE)
GRPCMSGTYPE_BCMD = 0
GRPCMSGTYPE_STRCMD = 1
GRPCMSGTYPE_NOTIFYEVENT = 2
GRPCMSGTYPE_REPORTALARM = 3



_PBREQUEST = _descriptor.Descriptor(
  name='PbRequest',
  full_name='GrpcDcopPb.PbRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='CmdLine', full_name='GrpcDcopPb.PbRequest.CmdLine', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=58,
)


_PBRESULT_COLVALUE = _descriptor.Descriptor(
  name='ColValue',
  full_name='GrpcDcopPb.PbResult.ColValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Type', full_name='GrpcDcopPb.PbResult.ColValue.Type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='iVal', full_name='GrpcDcopPb.PbResult.ColValue.iVal', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dwVal', full_name='GrpcDcopPb.PbResult.ColValue.dwVal', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='qwVal', full_name='GrpcDcopPb.PbResult.ColValue.qwVal', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dbVal', full_name='GrpcDcopPb.PbResult.ColValue.dbVal', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='strVal', full_name='GrpcDcopPb.PbResult.ColValue.strVal', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=347,
)

_PBRESULT_COL = _descriptor.Descriptor(
  name='Col',
  full_name='GrpcDcopPb.PbResult.Col',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ColVal', full_name='GrpcDcopPb.PbResult.Col.ColVal', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=349,
  serialized_end=401,
)

_PBRESULT = _descriptor.Descriptor(
  name='PbResult',
  full_name='GrpcDcopPb.PbResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Result', full_name='GrpcDcopPb.PbResult.Result', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Count', full_name='GrpcDcopPb.PbResult.Count', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Field', full_name='GrpcDcopPb.PbResult.Field', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Row', full_name='GrpcDcopPb.PbResult.Row', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MsgType', full_name='GrpcDcopPb.PbResult.MsgType', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Title', full_name='GrpcDcopPb.PbResult.Title', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='strResult', full_name='GrpcDcopPb.PbResult.strResult', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='NeId', full_name='GrpcDcopPb.PbResult.NeId', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_PBRESULT_COLVALUE, _PBRESULT_COL, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=401,
)


_ERRCODE = _descriptor.Descriptor(
  name='Errcode',
  full_name='GrpcDcopPb.Errcode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dwErrcode', full_name='GrpcDcopPb.Errcode.dwErrcode', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=403,
  serialized_end=431,
)

_PBRESULT_COLVALUE.containing_type = _PBRESULT
_PBRESULT_COL.fields_by_name['ColVal'].message_type = _PBRESULT_COLVALUE
_PBRESULT_COL.containing_type = _PBRESULT
_PBRESULT.fields_by_name['Row'].message_type = _PBRESULT_COL
_PBRESULT.fields_by_name['MsgType'].enum_type = _GRPCMSGTYPE
DESCRIPTOR.message_types_by_name['PbRequest'] = _PBREQUEST
DESCRIPTOR.message_types_by_name['PbResult'] = _PBRESULT
DESCRIPTOR.message_types_by_name['Errcode'] = _ERRCODE
DESCRIPTOR.enum_types_by_name['GrpcMsgType'] = _GRPCMSGTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PbRequest = _reflection.GeneratedProtocolMessageType('PbRequest', (_message.Message,), dict(
  DESCRIPTOR = _PBREQUEST,
  __module__ = 'dcopintf_pb2'
  # @@protoc_insertion_point(class_scope:GrpcDcopPb.PbRequest)
  ))
_sym_db.RegisterMessage(PbRequest)

PbResult = _reflection.GeneratedProtocolMessageType('PbResult', (_message.Message,), dict(

  ColValue = _reflection.GeneratedProtocolMessageType('ColValue', (_message.Message,), dict(
    DESCRIPTOR = _PBRESULT_COLVALUE,
    __module__ = 'dcopintf_pb2'
    # @@protoc_insertion_point(class_scope:GrpcDcopPb.PbResult.ColValue)
    ))
  ,

  Col = _reflection.GeneratedProtocolMessageType('Col', (_message.Message,), dict(
    DESCRIPTOR = _PBRESULT_COL,
    __module__ = 'dcopintf_pb2'
    # @@protoc_insertion_point(class_scope:GrpcDcopPb.PbResult.Col)
    ))
  ,
  DESCRIPTOR = _PBRESULT,
  __module__ = 'dcopintf_pb2'
  # @@protoc_insertion_point(class_scope:GrpcDcopPb.PbResult)
  ))
_sym_db.RegisterMessage(PbResult)
_sym_db.RegisterMessage(PbResult.ColValue)
_sym_db.RegisterMessage(PbResult.Col)

Errcode = _reflection.GeneratedProtocolMessageType('Errcode', (_message.Message,), dict(
  DESCRIPTOR = _ERRCODE,
  __module__ = 'dcopintf_pb2'
  # @@protoc_insertion_point(class_scope:GrpcDcopPb.Errcode)
  ))
_sym_db.RegisterMessage(Errcode)



_GRPCREQUEST = _descriptor.ServiceDescriptor(
  name='GrpcRequest',
  full_name='GrpcDcopPb.GrpcRequest',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=553,
  serialized_end=699,
  methods=[
  _descriptor.MethodDescriptor(
    name='ProcessRequest',
    full_name='GrpcDcopPb.GrpcRequest.ProcessRequest',
    index=0,
    containing_service=None,
    input_type=_PBREQUEST,
    output_type=_PBRESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CommandLineResult',
    full_name='GrpcDcopPb.GrpcRequest.CommandLineResult',
    index=1,
    containing_service=None,
    input_type=_PBREQUEST,
    output_type=_PBRESULT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GRPCREQUEST)

DESCRIPTOR.services_by_name['GrpcRequest'] = _GRPCREQUEST


_NOTIFY2NCS = _descriptor.ServiceDescriptor(
  name='Notify2NCS',
  full_name='GrpcDcopPb.Notify2NCS',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=701,
  serialized_end=768,
  methods=[
  _descriptor.MethodDescriptor(
    name='Notify',
    full_name='GrpcDcopPb.Notify2NCS.Notify',
    index=0,
    containing_service=None,
    input_type=_PBRESULT,
    output_type=_ERRCODE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_NOTIFY2NCS)

DESCRIPTOR.services_by_name['Notify2NCS'] = _NOTIFY2NCS

# @@protoc_insertion_point(module_scope)
